  .data
  .text
  .globl main
main:
  addi sp, sp, -1424
  sw ra, 1412(sp)
  addi t0, sp, 0
  addi t1, sp, 60
  sw t0, 0(t1)
  addi t0, sp, 64
  addi t1, sp, 124
  sw t0, 0(t1)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 128(sp)
  addi t0, sp, 128
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 132(sp)
  lw t0, 132(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 136(sp)
  addi t0, sp, 136
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 140(sp)
  lw t0, 140(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 144(sp)
  addi t0, sp, 144
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 148(sp)
  lw t0, 148(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 152(sp)
  addi t0, sp, 152
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 156(sp)
  lw t0, 156(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 160(sp)
  addi t0, sp, 160
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 164(sp)
  lw t0, 164(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 168(sp)
  addi t0, sp, 168
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 172(sp)
  lw t0, 172(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 176(sp)
  addi t0, sp, 176
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 180(sp)
  lw t0, 180(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 184(sp)
  addi t0, sp, 184
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 188(sp)
  lw t0, 188(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 192(sp)
  addi t0, sp, 192
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 196(sp)
  lw t0, 196(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 200(sp)
  addi t0, sp, 200
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 204(sp)
  lw t0, 204(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 208(sp)
  addi t0, sp, 208
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 212(sp)
  lw t0, 212(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 216(sp)
  addi t0, sp, 216
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 220(sp)
  lw t0, 220(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 224(sp)
  addi t0, sp, 224
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 228(sp)
  lw t0, 228(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 232(sp)
  addi t0, sp, 232
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 236(sp)
  lw t0, 236(sp)
  sw zero, 0(t0)
  addi t0, sp, 124
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 240(sp)
  addi t0, sp, 240
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 244(sp)
  lw t0, 244(sp)
  sw zero, 0(t0)
  addi t0, sp, 248
  addi t1, sp, 308
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 312(sp)
  addi t0, sp, 312
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 316(sp)
  li t0, 1
  lw t1, 316(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 320(sp)
  addi t0, sp, 320
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 324(sp)
  li t0, 2
  lw t1, 324(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 328(sp)
  addi t0, sp, 328
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 332(sp)
  li t0, 3
  lw t1, 332(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 336(sp)
  addi t0, sp, 336
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 340(sp)
  li t0, 4
  lw t1, 340(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 344(sp)
  addi t0, sp, 344
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 348(sp)
  li t0, 5
  lw t1, 348(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 352(sp)
  addi t0, sp, 352
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 356(sp)
  li t0, 6
  lw t1, 356(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 360(sp)
  addi t0, sp, 360
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 364(sp)
  li t0, 7
  lw t1, 364(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 368(sp)
  addi t0, sp, 368
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 372(sp)
  li t0, 8
  lw t1, 372(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 376(sp)
  addi t0, sp, 376
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 380(sp)
  li t0, 9
  lw t1, 380(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 384(sp)
  addi t0, sp, 384
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 388(sp)
  li t0, 10
  lw t1, 388(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 392(sp)
  addi t0, sp, 392
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 396(sp)
  li t0, 11
  lw t1, 396(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 400(sp)
  addi t0, sp, 400
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 404(sp)
  li t0, 12
  lw t1, 404(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 408(sp)
  addi t0, sp, 408
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 412(sp)
  li t0, 13
  lw t1, 412(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 416(sp)
  addi t0, sp, 416
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 420(sp)
  li t0, 14
  lw t1, 420(sp)
  sw t0, 0(t1)
  addi t0, sp, 308
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 424(sp)
  addi t0, sp, 424
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 428(sp)
  li t0, 15
  lw t1, 428(sp)
  sw t0, 0(t1)
  addi t0, sp, 432
  addi t1, sp, 492
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 496(sp)
  addi t0, sp, 496
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 500(sp)
  li t0, 1
  lw t1, 500(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 504(sp)
  addi t0, sp, 504
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 508(sp)
  li t0, 2
  lw t1, 508(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 512(sp)
  addi t0, sp, 512
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 516(sp)
  li t0, 3
  lw t1, 516(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 520(sp)
  addi t0, sp, 520
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 524(sp)
  li t0, 4
  lw t1, 524(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 528(sp)
  addi t0, sp, 528
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 532(sp)
  li t0, 5
  lw t1, 532(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 536(sp)
  addi t0, sp, 536
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 540(sp)
  li t0, 6
  lw t1, 540(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 544(sp)
  addi t0, sp, 544
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 548(sp)
  li t0, 7
  lw t1, 548(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 552(sp)
  addi t0, sp, 552
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 556(sp)
  li t0, 8
  lw t1, 556(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 560(sp)
  addi t0, sp, 560
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 564(sp)
  li t0, 9
  lw t1, 564(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 568(sp)
  addi t0, sp, 568
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 572(sp)
  li t0, 10
  lw t1, 572(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 576(sp)
  addi t0, sp, 576
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 580(sp)
  li t0, 11
  lw t1, 580(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 584(sp)
  addi t0, sp, 584
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 588(sp)
  li t0, 12
  lw t1, 588(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 592(sp)
  addi t0, sp, 592
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 596(sp)
  li t0, 13
  lw t1, 596(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 600(sp)
  addi t0, sp, 600
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 604(sp)
  li t0, 14
  lw t1, 604(sp)
  sw t0, 0(t1)
  addi t0, sp, 492
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 608(sp)
  addi t0, sp, 608
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 612(sp)
  li t0, 15
  lw t1, 612(sp)
  sw t0, 0(t1)
  addi t0, sp, 616
  addi t1, sp, 676
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 680(sp)
  addi t0, sp, 680
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 684(sp)
  li t0, 1
  lw t1, 684(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 688(sp)
  addi t0, sp, 688
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 692(sp)
  li t0, 2
  lw t1, 692(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 696(sp)
  addi t0, sp, 696
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 700(sp)
  li t0, 3
  lw t1, 700(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 704(sp)
  addi t0, sp, 704
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 708(sp)
  li t0, 4
  lw t1, 708(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 712(sp)
  addi t0, sp, 712
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 716(sp)
  li t0, 5
  lw t1, 716(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 720(sp)
  addi t0, sp, 720
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 724(sp)
  li t0, 6
  lw t1, 724(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 728(sp)
  addi t0, sp, 728
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 732(sp)
  li t0, 7
  lw t1, 732(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 736(sp)
  addi t0, sp, 736
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 740(sp)
  li t0, 8
  lw t1, 740(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 744(sp)
  addi t0, sp, 744
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 748(sp)
  li t0, 9
  lw t1, 748(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 752(sp)
  addi t0, sp, 752
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 756(sp)
  li t0, 10
  lw t1, 756(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 760(sp)
  addi t0, sp, 760
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 764(sp)
  li t0, 11
  lw t1, 764(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 768(sp)
  addi t0, sp, 768
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 772(sp)
  li t0, 12
  lw t1, 772(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 776(sp)
  addi t0, sp, 776
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 780(sp)
  li t0, 13
  lw t1, 780(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 784(sp)
  addi t0, sp, 784
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 788(sp)
  li t0, 14
  lw t1, 788(sp)
  sw t0, 0(t1)
  addi t0, sp, 676
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 792(sp)
  addi t0, sp, 792
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 796(sp)
  li t0, 15
  lw t1, 796(sp)
  sw t0, 0(t1)
  addi t0, sp, 800
  addi t1, sp, 820
  sw t0, 0(t1)
  addi t0, sp, 824
  addi t1, sp, 884
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 888(sp)
  addi t0, sp, 888
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 892(sp)
  li t0, 1
  lw t1, 892(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 896(sp)
  addi t0, sp, 896
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 900(sp)
  li t0, 2
  lw t1, 900(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 12
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 904(sp)
  addi t0, sp, 904
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 908(sp)
  li t0, 3
  lw t1, 908(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 912(sp)
  addi t0, sp, 912
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 916(sp)
  li t0, 4
  lw t1, 916(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 920(sp)
  addi t0, sp, 920
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 924(sp)
  lw t0, 924(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 1
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 928(sp)
  addi t0, sp, 928
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 932(sp)
  lw t0, 932(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 936(sp)
  addi t0, sp, 936
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 940(sp)
  li t0, 7
  lw t1, 940(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 944(sp)
  addi t0, sp, 944
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 948(sp)
  lw t0, 948(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 2
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 952(sp)
  addi t0, sp, 952
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 956(sp)
  lw t0, 956(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 960(sp)
  addi t0, sp, 960
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 964(sp)
  li t0, 10
  lw t1, 964(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 968(sp)
  addi t0, sp, 968
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 972(sp)
  li t0, 11
  lw t1, 972(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 3
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 976(sp)
  addi t0, sp, 976
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 980(sp)
  li t0, 12
  lw t1, 980(sp)
  sw t0, 0(t1)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 984(sp)
  addi t0, sp, 984
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 988(sp)
  lw t0, 988(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 992(sp)
  addi t0, sp, 992
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 996(sp)
  lw t0, 996(sp)
  sw zero, 0(t0)
  addi t0, sp, 884
  lw t0, 0(t0)
  li t1, 4
  li t2, 12
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1000(sp)
  addi t0, sp, 1000
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1004(sp)
  lw t0, 1004(sp)
  sw zero, 0(t0)
  addi t0, sp, 1008
  addi t1, sp, 1020
  sw t0, 0(t1)
  addi t0, sp, 1024
  addi t1, sp, 1120
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1124(sp)
  addi t0, sp, 1124
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1128(sp)
  addi t0, sp, 1128
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1132(sp)
  li t0, 1
  lw t1, 1132(sp)
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1136(sp)
  addi t0, sp, 1136
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1140(sp)
  addi t0, sp, 1140
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1144(sp)
  li t0, 2
  lw t1, 1144(sp)
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1148(sp)
  addi t0, sp, 1148
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1152(sp)
  addi t0, sp, 1152
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1156(sp)
  li t0, 3
  lw t1, 1156(sp)
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1160(sp)
  addi t0, sp, 1160
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1164(sp)
  addi t0, sp, 1164
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1168(sp)
  li t0, 4
  lw t1, 1168(sp)
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1172(sp)
  addi t0, sp, 1172
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1176(sp)
  addi t0, sp, 1176
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1180(sp)
  li t0, 5
  lw t1, 1180(sp)
  sw t0, 0(t1)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1184(sp)
  addi t0, sp, 1184
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1188(sp)
  addi t0, sp, 1188
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1192(sp)
  lw t0, 1192(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1196(sp)
  addi t0, sp, 1196
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1200(sp)
  addi t0, sp, 1200
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1204(sp)
  lw t0, 1204(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1208(sp)
  addi t0, sp, 1208
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1212(sp)
  addi t0, sp, 1212
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1216(sp)
  lw t0, 1216(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1220(sp)
  addi t0, sp, 1220
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1224(sp)
  addi t0, sp, 1224
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1228(sp)
  lw t0, 1228(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1232(sp)
  addi t0, sp, 1232
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1236(sp)
  addi t0, sp, 1236
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1240(sp)
  lw t0, 1240(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1244(sp)
  addi t0, sp, 1244
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1248(sp)
  addi t0, sp, 1248
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1252(sp)
  lw t0, 1252(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 48
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1256(sp)
  addi t0, sp, 1256
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1260(sp)
  addi t0, sp, 1260
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1264(sp)
  lw t0, 1264(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1268(sp)
  addi t0, sp, 1268
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1272(sp)
  addi t0, sp, 1272
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1276(sp)
  lw t0, 1276(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1280(sp)
  addi t0, sp, 1280
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1284(sp)
  addi t0, sp, 1284
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1288(sp)
  lw t0, 1288(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1292(sp)
  addi t0, sp, 1292
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1296(sp)
  addi t0, sp, 1296
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1300(sp)
  lw t0, 1300(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1304(sp)
  addi t0, sp, 1304
  lw t0, 0(t0)
  li t1, 16
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1308(sp)
  addi t0, sp, 1308
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1312(sp)
  lw t0, 1312(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1316(sp)
  addi t0, sp, 1316
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1320(sp)
  addi t0, sp, 1320
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1324(sp)
  lw t0, 1324(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1328(sp)
  addi t0, sp, 1328
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1332(sp)
  addi t0, sp, 1332
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1336(sp)
  lw t0, 1336(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1340(sp)
  addi t0, sp, 1340
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1344(sp)
  addi t0, sp, 1344
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1348(sp)
  lw t0, 1348(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1352(sp)
  addi t0, sp, 1352
  lw t0, 0(t0)
  li t1, 1
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1356(sp)
  addi t0, sp, 1356
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1360(sp)
  lw t0, 1360(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1364(sp)
  addi t0, sp, 1364
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1368(sp)
  addi t0, sp, 1368
  lw t0, 0(t0)
  li t1, 4
  mul t1, zero, t1
  add t0, t0, t1
  sw t0, 1372(sp)
  lw t0, 1372(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1376(sp)
  addi t0, sp, 1376
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1380(sp)
  addi t0, sp, 1380
  lw t0, 0(t0)
  li t1, 1
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1384(sp)
  lw t0, 1384(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1388(sp)
  addi t0, sp, 1388
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1392(sp)
  addi t0, sp, 1392
  lw t0, 0(t0)
  li t1, 2
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1396(sp)
  lw t0, 1396(sp)
  sw zero, 0(t0)
  addi t0, sp, 1120
  lw t0, 0(t0)
  li t1, 1
  li t2, 48
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1400(sp)
  addi t0, sp, 1400
  lw t0, 0(t0)
  li t1, 2
  li t2, 16
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1404(sp)
  addi t0, sp, 1404
  lw t0, 0(t0)
  li t1, 3
  li t2, 4
  mul t2, t1, t2
  add t0, t0, t2
  sw t0, 1408(sp)
  lw t0, 1408(sp)
  sw zero, 0(t0)
  li t0, 4
  mv a0, t0
  lw ra, 1412(sp)
  addi sp, sp, 1424
  ret

